# Generated by Django 5.1.7 on 2025-08-16 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('teachers', '0005_delete_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(choices=[('mcq', 'Multiple Choice Questions'), ('descriptive', 'Descriptive Questions')], max_length=20)),
                ('max_level_reached', models.IntegerField(default=0)),
                ('feedback_level', models.CharField(choices=[('basic', 'Basic Knowledge'), ('intermediate', 'Intermediate Knowledge'), ('advanced', 'Advanced Knowledge'), ('excellent', 'Excellent Knowledge')], max_length=20)),
                ('feedback_message', models.TextField()),
                ('total_questions_attempted', models.IntegerField(default=0)),
                ('total_correct_answers', models.IntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.syllabus')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloom_level', models.CharField(max_length=20)),
                ('question_text', models.TextField()),
                ('student_answer', models.TextField()),
                ('correct_option', models.CharField(blank=True, max_length=500, null=True)),
                ('selected_option', models.CharField(blank=True, max_length=500, null=True)),
                ('expected_keywords', models.JSONField(blank=True, null=True)),
                ('matched_keywords', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('score_percentage', models.FloatField(default=0.0)),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='feedback.quizfeedback')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
