# Generated by Django 5.2.1 on 2025-08-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
